# .gitpod.yml
# Reproducible Hugo (extended) + Go + Node dev env for Hugoplate
# - Installs Hugo v0.147.3 (extended)
# - Installs Go 1.23.3 (for Hugo Modules)
# - Tidy Hugo modules + install npm deps
# - Starts local dev server

tasks:
  - name: Setup & Dev
    before: |
      # Remove distro Hugo (often too old)
      sudo apt-get update -y
      sudo apt-get remove -y hugo || true

      # Install Hugo (extended)
      export HUGO_VER=0.147.3
      wget -q https://github.com/gohugoio/hugo/releases/download/v${HUGO_VER}/hugo_extended_${HUGO_VER}_Linux-64bit.tar.gz
      tar -xzf hugo_extended_${HUGO_VER}_Linux-64bit.tar.gz
      sudo mv hugo /usr/local/bin/
      hugo version

      # Install Go (needed for Hugo Modules)
      export GO_VER=1.23.3
      wget -q https://dl.google.com/go/go${GO_VER}.linux-amd64.tar.gz
      sudo rm -rf /usr/local/go
      sudo tar -C /usr/local -xzf go${GO_VER}.linux-amd64.tar.gz
      echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
      export PATH=$PATH:/usr/local/go/bin
      go version
    init: |
      # Pull theme/modules & tidy
      git submodule update --init --recursive || true
      hugo mod clean
      hugo mod get -u
      hugo mod tidy

      # Node deps & project setup
      npm ci || npm install
      npm run project-setup || true
    command: |
      npm run dev

# Expose Hugo’s default dev port
ports:
  - port: 1313
    onOpen: open-preview
    visibility: public